version: '3.8'
services:
  mongodb:
    image: mongo:7.0.14
    container_name: mongodb_wamesports
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: